name: "Summer Uniform"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Summer_School.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset