base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/Gojo2/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/Gojo2/face-mesh.uasset
hair:
  mesh_path: /Game/Costumes/Player/Gojo2/hair-mesh.uasset
name: Strongest Sorcerer Attire (No mask)
