base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/Tifa/costume-mesh.uasset
face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset
hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset
name: Tifa's Outfit
