base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/Joker/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/Joker/face-mesh.uasset
hair:
  mesh_path: /Game/Costumes/Player/Joker/hair-mesh.uasset
name: Joker's Outfit
