base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/P3P/costume-mesh.uasset
face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset
hair:
  mesh_path: /Game/Costumes/Player/P3P/hair-mesh.uasset
name: P3P
