base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/Fubukinya/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/Fubukinya/face-mesh.uasset
hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset
name: WDO Uniform
