name: "Blue Shorts"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Swimsuit.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset