base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Winter_School_Battle.uasset
face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset
hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset
name: Uniform & Armband
