name: "Dorm Apron"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Apron.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair_Kerchief.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset