base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/Onemid/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/Onemid/face-mesh.uasset
hair:
  mesh_path: /Game/Costumes/Player/Onemid/hair-mesh.uasset
name: Monkey D Luffy Outfit
