base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/OneMidHatBackSmileyFace/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/OneMidHatBackSmileyFace/face-mesh.uasset
hair:
  mesh_path: /Game/Costumes/Player/OneMidHatBackSmileyFace/hair-mesh.uasset
name: Monkey D Luffy Outfit (Hat on Back)
