base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset
costume:
  mesh_path: /Game/Costumes/Player/OneMidHatHeadSmileyFace/costume-mesh.uasset
face:
  mesh_path: /Game/Costumes/Player/OneMidHatHeadSmileyFace/face-mesh.uasset
hair:
  mesh_path: /Game/Costumes/Player/OneMidHatHeadSmileyFace/hair-mesh.uasset
name: Monkey D Luffy (Hat on Head)
